services:
  backend:
    build: .
    container_name: dealer-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
      - ./company-logos:/dealergestor/company-logos
